### ISSUE TITLE
Enforce constants are declared at the top of the file

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#159]
We should enforce constants are only allowed at the top of the file just after file name definition.
Then the structure of an AirScript file could look like:

```
## Air name definition
...

## Constant declarations
...

## AIR source sections
...
```
_Originally proposed by @grjte in https://github.com/0xPolygonMiden/air-script/pull/152#discussion_r1111792918_

**Comment by bobbinth** [comment]
@tohrnii @grjte - is this still relevant, or should we close this?

**Comment by bobbinth** [comment]
@bitwalker - we now allow constants to be declared anywhere, right? If so, I think we can close this issue.

**Comment by bitwalker** [comment]
@bobbinth Yes, there is no ordering requirement on declarations now, so I'll go ahead and close this. The original issue seems to want to restrict the syntax, rather than loosen it up, but that feels more like a stylistic choice rather than something we should enforce in the parser, so I'd probably close this either way.
