### ISSUE TITLE
Tracking issue: AirScript codegen for constraint evaluation logic in Miden assembly

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/air-script#164]
### Goal(s)
- be able to generate constraint evaluation logic in Miden assembly from a given AIR defined in AirScript

### Details

This requires writing a new code generation backend to take the `AirIR` and output `masm` code for constraint evaluation that will work with the STARK verifier written in Miden Assembly (not yet completed).

The generated code will essentially fit into the STARK verifier at the equivalent place as [this function call](https://github.com/facebook/winterfell/blob/main/verifier/src/lib.rs#L188) in Winterfell.

The new backend therefore needs to handle code generation for equivalent functionality to the [`evaluate_constraints` function](https://github.com/facebook/winterfell/blob/main/verifier/src/evaluator.rs#L14) in Winterfell.

The caveat to this is that we may not need to handle [combining evaluations](https://github.com/facebook/winterfell/blob/main/verifier/src/evaluator.rs#L57) as is done in the Winterfell function. This could be done in a different way, depending on the design of the Miden Assembly STARK verifier.

The first step of this is clarify the [design for the STARK verifier](https://github.com/0xPolygonMiden/miden-vm/issues/717) and use that to identify the interface (i.e. what stack and memory should look like) and the procedures that need to be generated in Miden assembly.

```[tasklist]
### Must have
- [ ] https://github.com/0xPolygonMiden/air-script/issues/166
```

```[tasklist]
### Nice to have
```

## Working group:
@Al-Kindi-0, @grjte, @Overcastan, @tohrnii 

<details>
<summary>Workflow</summary>
    
- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
    
</details>

### Coordinator: @Al-Kindi-0
<details>
    
The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>

**Comment by Al-Kindi-0** [comment]
A few preliminary ideas regarding the generation of the equivalent of `evaluate_constraints` function in `masm`.
The `evaluate_constraints` function takes as input:

1. `air: ProcessorAir`.
2. `composition_coefficients: ConstraintCompositionCoefficients<E>`.
3.  `main_trace_frame: EvaluationFrame<E>`.
4. `aux_trace_frame: Option<EvaluationFrame<E>>`
5.  `aux_rand_elements: AuxTraceRandElements<E>`
6. `x: E`

In what follows, we can forget for a moment about the auxiliary trace and hence auxiliary random elements as well. I will also focus only on transition constraints.
The `evaluate_constraints` essentially takes an evaluation frame, which is just two rows of length equal to the width of the execution trace, and evaluates a bunch of multivariate polynomials at this evaluation frame.
More precisely, let `[[x_0, ..., x_w], [y_0, ..., y_w]]` be the value of our evaluation frame then `evaluate_constraints` performs the following:
```
for i in range(number_of_constraints):
     result[i] = transition_constraint_i([[x_0, ..., x_w], [y_0, ..., y_w]])
```
where `transition_constraint_i` is a multivariate polynomial in $(X_0, \cdots, X_w, Y_0, \cdots, Y_w)$.
After computing the `result` array, the values are reduced to a single value using the `composition_coefficients`.
I glossed over the periodic values but they should be straightforward to integrate in the above.
The main problem in the above is now reduced to the problem of evaluating a bunch of multivariate polynomials at  `[[x_0, ..., x_w], [y_0, ..., y_w]]`.
The Miden VM constraints are divided into different sets:

1. System constraints.
2. Program decoder constraints.
3. Stack constraints.
4. Range checker constraints.
5. Chiplets constraints.

Each of these constraints are evaluated only[^1] on a subset of `x_0, ..., x_w` and  `y_0, ..., y_w` and thus it makes sense to generate the `masm` code for constraint evaluation separately for each of the above 5 groups. On the other hand, constraints belonging to the same group should be evaluated simultaneously in order to avoid recomputing common sub-expressions. More precisely, each multivariate polynomial representing a certain constraint can be computed using a DAG where the leafs are the values  `x_0, ..., x_w` and  `y_0, ..., y_w`, a (one and only one) root representing the value of the evaluation and the remaining nodes representing intermediate expressions. Now, since the leafs are the same for all constraints in the same group it is very likely that many of the intermediate expressions will be shared among two or more of the constraints within a group. Thus it makes sense to compute these once and then store them in memory for later use. This should be benchmarked against the naive approach but since  `x_0, ..., x_w` and  `y_0, ..., y_w` are going to be stored in memory, and hence should be loaded (again) in order to re-compute the sub-expression, the costs of storing common sub-expressions should be justified.
Taking the above into account the stack and memory configuration, when a procedure evaluating all constraints within one of the 5 above groups is called, can be visualized as follows:
![stark_mem_stack](https://user-images.githubusercontent.com/82364884/222837705-2f3370fa-fd7d-4aa8-8a41-13433dfec8db.png)
One thing worth clarifying is in relation to memory management. The fact that the constraints are fixed means that everything is known statically and hence memory management can be reduced to a bunch of hardcoded offsets against an address given by `ptr`.
Common sub-expression factorization is only one of several potential optimizations that can be done once and for all to generate (near) optimal `masm` code. Other optimizations can include scheduling using `dup` and `movdn` in order to use a common sub-expression latter on. This might be useful in case a common sub-expression is shared by only two expressions and thus using memory to save the common sub-expression might not be justified.

[^1]: Please correct me if I am wrong.

**Comment by bobbinth** [comment]
@Al-Kindi-0  - thank you! This is a great write up! A few thoughts from my end.

First, I don't think we should worry about optimizing constraint evaluation just yet. As the first step, we should output evaluation logic which is as simple as possible even if it is 10x (or more) slower than what is optimal. So, I wouldn't worry about identifying groups of constraints which should be evaluated together.

Second, I agree that we should have `evaluate_constraints` procedure which is equivalent to the [evaluate_constraints()](https://github.com/facebook/winterfell/blob/main/verifier/src/evaluator.rs#L14) function in Winterfell - but I wonder if the interface could work as follows:

The return value of `evaluate_constraints` would be just a single element in degree two extension field (same as in Winterfell). So, there is no need to have multiple results written to memory, and instead we can return the result via the stack (i.e., top two elements).

The inputs would be provided to `evaluate_constraints` via procedure locals. That is, the caller would pre-populate procedure locals of the callee with relevant inputs. The inputs would be laid out like this:

1. $n / 2$ locals for the main frame where $n$ is the number of columns in the main trace segment rounded up to the value divisible by 4. In case of Miden, $n$ would be $72$ and thus the number of locals would be $36$. Here each local would contain $4$ column values.
2. $m$ locals for the auxiliary frame where $m$ is the number of columns in the auxiliary trace segment rounded up to the value divisible by 2. In case of Miden, $m$ would be $10$ (since we have $9$ auxiliary columns) and thus the number of locals would be $10$. Here each local would contain $2$ column values (because each value is in the extension field).
3. $c / 2$ locals for $c$ composition coefficients where each composition coefficient is an element in the extension field (I'm not sure how many of these we currently have in Miden - but the number here is usually equal to the number of unique transition + boundary constraints).
4. $a / 2$ locals for $a$ random values where each random value is an element in the extension field (I'm not sure about the exact number we have, but it is probably somewhere around $12$).
5. $p / 4$ locals for $p$ periodic column values where each periodic column value is a base field element (I'm not sure how many of these we have, but probably around 6 or 8).
6. One random out-of-domain point $x$ (in the extension field). This can probably be passed via the stack.
7. Several u32 values (e.g., trace length, blowup factor) needed to compute degree adjustment factors for constraints.

Computing these degree adjustment factors could be a pretty tricky thing as we need to perform exponentiation in the extension field. I'm imagining this to be a pretty involved computation which could take 1K - 2K cycles (if not more).

**Comment by Al-Kindi-0** [comment]
> 1. $n / 2$ locals for the main frame where $n$ is the number of columns in the main trace segment rounded up to the value divisible by 4. In case of Miden, $n$ would be $72$ and thus the number of locals would be $36$. Here each local would contain $4$ column values.

For the OOD frame, the elements are in the extension field even for the main trace. We have 72 columns and thus 144 elements. If we include the 9 auxiliary columns, we have in total 162 base elements for the current row. I am treating the main and auxiliary parts together since this is the way we hash them in order to reseed the random coin. This is also how they are treated with regards to `advice_pipe`. 
The same goes for the next row of the OOD frame.

> 2. $m$ locals for the auxiliary frame where $m$ is the number of columns in the auxiliary trace segment rounded up to the value divisible by 2. In case of Miden, $m$ would be $10$ (since we have $9$ auxiliary columns) and thus the number of locals would be $10$. Here each local would contain $2$ column values (because each value is in the extension field).

Included in the above remark.

> 3. $c / 2$ locals for $c$ composition coefficients where each composition coefficient is an element in the extension field (I'm not sure how many of these we currently have in Miden - but the number here is usually equal to the number of unique transition + boundary constraints).

Yes, the number of composition coefficients (all are ExtFelt) is equal to the total number of unique transition and boundary constraints. Currently, we have:

1. 188 main transition constraints
2. 2 aux transition constraints
3. 45 boundary constraints divided into two groups

> 4. $a / 2$ locals for $a$ random values where each random value is an element in the extension field (I'm not sure about the exact number we have, but it is probably somewhere around $12$).

Do you mean for the auxiliary trace? Then we have 16 such ExtFelt.

> 6. $p / 4$ locals for $p$ periodic column values where each periodic column value is a base field element (I'm not sure how many of these we have, but probably around 6 or 8).

These are also ExtFelt. We currently have 29 values (ExtFelt) of these.

> 8. One random out-of-domain point $x$ (in the extension field). This can probably be passed via the stack.
Makes sense

> 9. Several u32 values (e.g., trace length, blowup factor) needed to compute degree adjustment factors for constraints. These could probably also be passed in via the stack.

I am working under the assumption that the blowup factor is equal to $8$, are you thinking of making the implementation generic over that?

**Comment by bobbinth** [comment]
Closing this as the initial implementation has been complete via several PRs.
