### ISSUE TITLE
Modify match syntax

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/air-script#224]
> I'm not sure I'm fully convinced about match enf anyway, since it doesn't really save that much. I think it would be much more useful if we allowed having a selector after it,
 
```
match enf when a:
    apply_constraints([b, c])
    apply_other_contraints([d, e, f])
```

_Originally posted by @grjte in https://github.com/0xPolygonMiden/air-script/pull/218#discussion_r1134407485_

**Comment by bobbinth** [comment]
Is the idea here that constraints in `apply_constraints` would be multiplied by `a` and constraints in `apply_other_constraints` would be multiplied by `(1 - a)`?

**Comment by bobbinth** [comment]
I think the current syntax is useful because it will allow us to perform some analysis in the future easier. For example, if we have:
```
match enf:
    apply_constraints([b, c]) when a
    apply_other_contraints([d, e, f]) when !a
```
Checking that `a` and `!a` are actually mutually exclusive conditions would be easier than if we have:
```
enf apply_constraints([b, c]) when a
enf apply_other_contraints([d, e, f]) when !a
```

Regarding the original post, I think I understand the intent now (but correct me if I'm wrong). If my understanding is correct, maybe we use a different construct - e.g., something like `enf when` (without the `match`). For example:
```
enf when a:
    apply_constraints([b, c])
    apply_other_contraints([d, e, f])
```
In this case, both sets of constraints would be multiplied by $a$. This could simplify things when $a$ is a complex expression.

**Comment by tohrnii** [comment]
> I think the current syntax is useful because it will allow us to perform some analysis in the future easier.

I agree with you but currently the way we have implemented parsing for these blocks, we lose this information at the parser level. So, either we change the way we store these in the AST (now or in future), or not rely on the user to write these constraints correctly. For eg, users could incorrectly use selector combinations that are not mutually exclusive (so we will have to check for validity of these mutually exclusive selectors) or use mutually exclusive selector conditions but outside of a `match` block so we will have to check across all constraints if we can combine any that have mutually exclusive selector conditions.

To me it seems like there is an argument to be made for both cases and maybe we should keep it as is for now and revisit this after we have written more miden constraints in AirScript as we'll have a slightly better idea on what makes sense from UX perspective as well?

> Regarding the original post, I think I understand the intent now (but correct me if I'm wrong). If my understanding is correct, maybe we use a different construct - e.g., something like enf when (without the match)

Makes sense

**Comment by tohrnii** [comment]
Closing this issue since we want to stick with current syntax. Opened #231 for the new syntax proposed by @bobbinth above.

**Comment by grjte** [comment]
Sorry for the very late reply here. I missed this discussion somehow.

> Regarding the original post, I think I understand the intent now (but correct me if I'm wrong). If my understanding is correct, maybe we use a different construct - e.g., something like `enf when` (without the `match`). For example:
> 
> ```
> enf when a:
>     apply_constraints([b, c])
>     apply_other_contraints([d, e, f])
> ```
> 
> In this case, both sets of constraints would be multiplied by a. This could simplify things when a is a complex expression.

Yes, this was the original intent of my comment.

> I think the current syntax is useful because it will allow us to perform some analysis in the future easier. For example, if we have:
> 
> ```
> match enf:
>     apply_constraints([b, c]) when a
>     apply_other_contraints([d, e, f]) when !a
> ```
> 
> Checking that `a` and `!a` are actually mutually exclusive conditions would be easier than if we have:
> 
> ```
> enf apply_constraints([b, c]) when a
> enf apply_other_contraints([d, e, f]) when !a
> ```

My biggest issue with this syntax is that it's not very clear what we're matching on. In Rust when we we use match we specify what we're matching `match x { ... }`, and we do the same thing with switch statements in C, etc. There's no specification in the syntax here for what the rules of the match block are, since `enf` is just a keyword that means to enforce a constraint. Additionally, `match` is for exhaustive matching against a particular thing, and it doesn't seem like that's the intent here. If we're doing something non-exhaustive where we match against conditions from the top to the bottom , then switch seems better.

It would make more sense to me if we had something like the following:

```
switch enf:
    case a:
        apply_constraints([b, c])
    case !a:
        apply_other_contraints([d, e, f])
```

or even:

```
switch enf:
    when a:
        apply_constraints([b, c])
    when !a:
        apply_other_contraints([d, e, f])
```

**Comment by bobbinth** [comment]
> It would make more sense to me if we had something like the following:
> ```
> switch enf:
>     case a:
>         apply_constraints([b, c])
>     case !a:
>         apply_other_contraints([d, e, f])
> ```
> 
> or even:
> 
> ```
> switch enf:
>     when a:
>         apply_constraints([b, c])
>     when !a:
>         apply_other_contraints([d, e, f])
> ```
> 
> or even
> 
> ```
> match enf:
>     when a:
>         apply_constraints([b, c])
>     when !a:
>         apply_other_contraints([d, e, f])
> ```

I actually don't see any of these as too different from:
```
match enf:
  apply_constraints([b, c]) when a
  apply_other_contraints([d, e, f]) when !a
```
And I think this is more consistent with how we do other things where we put "statement modifies" at the end (i.e., list comprehension).

I think `match enf` may be a bit inconsistent, and maybe `enf match` is better (I don't really like `switch` - but that could be used too).

**Comment by bobbinth** [comment]
Superseded by #231.
